"""empty message

Revision ID: 33c49d4139e4
Revises: 
Create Date: 2023-08-13 06:14:06.073433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c49d4139e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=500), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('first_name', sa.String(length=500), nullable=False),
    sa.Column('last_name', sa.String(length=500), nullable=False),
    sa.Column('primary_email', sa.String(length=500), nullable=False),
    sa.Column('gender', sa.String(length=500), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('secondary_email', sa.String(length=500), nullable=True),
    sa.Column('bsc_year_of_passing', sa.Integer(), nullable=True),
    sa.Column('ms_year_of_passing', sa.Integer(), nullable=True),
    sa.Column('bsc_cgpa', sa.Float(), nullable=True),
    sa.Column('ms_cgpa', sa.Float(), nullable=True),
    sa.Column('bsc_university', sa.String(length=500), nullable=True),
    sa.Column('ms_university', sa.String(length=500), nullable=True),
    sa.Column('github_link', sa.String(length=500), nullable=True),
    sa.Column('linkedin_link', sa.String(length=500), nullable=True),
    sa.Column('website_link', sa.String(length=500), nullable=True),
    sa.Column('current_address', sa.String(length=1000), nullable=True),
    sa.Column('gre_verbal_quant_score', sa.Integer(), nullable=True),
    sa.Column('gre_awa_score', sa.Float(), nullable=True),
    sa.Column('toefl_score', sa.Integer(), nullable=True),
    sa.Column('ielts_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_link'),
    sa.UniqueConstraint('linkedin_link'),
    sa.UniqueConstraint('password_hash'),
    sa.UniqueConstraint('primary_email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('website_link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
